//! Verify subcommands.

use std::path::PathBuf;

/// Arguments for end-to-end verification.
#[derive(Debug, clap::Args)]
pub struct VerifyRunArgs {
    /// Airdrop configuration file used for proof/signature binding checks.
    #[arg(
        long,
        env = "CONFIG_FILE",
        value_name = "CONFIG_FILE",
        default_value = "config.json"
    )]
    pub config: PathBuf,
    /// Path to the verifying key file.
    #[arg(
        long,
        env = "VERIFYING_KEY_FILE",
        value_name = "VERIFYING_KEY_FILE",
        default_value = "setup-sapling-vk.params"
    )]
    pub vk: PathBuf,
    /// Signed submission file generated by `claim sign`.
    #[arg(long, env = "SUBMISSION_IN", default_value = "claim-submission.json")]
    pub submission_in: PathBuf,
    /// Message payload file used when signing.
    #[arg(
        long,
        env = "MESSAGE_FILE",
        value_name = "MESSAGE_FILE",
        default_value = "claim-message.bin"
    )]
    pub msg: PathBuf,
}

/// Arguments for proof verification.
#[derive(Debug, clap::Args)]
pub struct VerifyProofArgs {
    /// Airdrop configuration file used to bind expected roots and scheme.
    #[arg(
        long,
        env = "CONFIG_FILE",
        value_name = "CONFIG_FILE",
        default_value = "config.json"
    )]
    pub config: PathBuf,
    /// Path to the verifying key file.
    #[arg(
        long,
        env = "VERIFYING_KEY_FILE",
        value_name = "VERIFYING_KEY_FILE",
        default_value = "setup-sapling-vk.params"
    )]
    pub vk: PathBuf,
    /// JSON file containing claim proofs.
    #[arg(long, env = "PROOFS_IN", default_value = "claim-proofs.json")]
    pub proofs_in: PathBuf,
}

/// Arguments for signature verification.
#[derive(Debug, clap::Args)]
pub struct VerifySignatureArgs {
    /// Airdrop configuration file used to bind expected target-id and pool.
    #[arg(
        long,
        env = "CONFIG_FILE",
        value_name = "CONFIG_FILE",
        default_value = "config.json"
    )]
    pub config: PathBuf,
    /// Signed submission file generated by `claim sign`.
    #[arg(long, env = "SUBMISSION_IN", default_value = "claim-submission.json")]
    pub submission_in: PathBuf,
    /// Message payload file used when signing.
    #[arg(
        long,
        env = "MESSAGE_FILE",
        value_name = "MESSAGE_FILE",
        default_value = "claim-message.bin"
    )]
    pub msg: PathBuf,
}

/// Verify command group.
#[derive(Debug, clap::Subcommand)]
pub enum VerifyCommands {
    /// Recommended end-to-end verification:
    /// `verify proof -> verify signature`.
    Run {
        #[command(flatten)]
        args: VerifyRunArgs,
    },
    /// Verify claim proofs from a proofs file.
    Proof {
        #[command(flatten)]
        args: VerifyProofArgs,
    },
    /// Verify signatures in a signed claim submission.
    Signature {
        #[command(flatten)]
        args: VerifySignatureArgs,
    },
}
