//! Verify subcommands.

use std::path::PathBuf;

use zair_sdk::commands::OrchardParamsMode;

use super::constants::{
    DEFAULT_CONFIG_FILE, DEFAULT_ORCHARD_PARAMS_FILE, DEFAULT_ORCHARD_PARAMS_MODE,
    DEFAULT_PROOFS_FILE, DEFAULT_SAPLING_VK_FILE, DEFAULT_SUBMISSION_FILE, ZAIR_CONFIG_FILE,
    ZAIR_MESSAGE_FILE, ZAIR_MESSAGES_FILE, ZAIR_ORCHARD_PARAMS_FILE, ZAIR_ORCHARD_PARAMS_MODE,
    ZAIR_PROOFS_IN, ZAIR_SAPLING_VK_FILE, ZAIR_SUBMISSION_IN,
};
use super::parse_orchard_params_mode;

/// Arguments for end-to-end verification.
#[derive(Debug, clap::Args)]
pub struct VerifyRunArgs {
    /// Airdrop configuration file used for proof/signature binding checks.
    #[arg(
        long,
        env = ZAIR_CONFIG_FILE,
        value_name = "CONFIG_FILE",
        default_value = DEFAULT_CONFIG_FILE
    )]
    pub config: PathBuf,
    /// Path to the Sapling verifying key file.
    #[arg(
        long = "sapling-vk",
        env = ZAIR_SAPLING_VK_FILE,
        value_name = "SAPLING_VK_FILE",
        default_value = DEFAULT_SAPLING_VK_FILE
    )]
    pub sapling_vk: PathBuf,
    /// Path to the Orchard Halo2 params file.
    #[arg(
        long,
        env = ZAIR_ORCHARD_PARAMS_FILE,
        value_name = "ORCHARD_PARAMS_FILE",
        default_value = DEFAULT_ORCHARD_PARAMS_FILE
    )]
    pub orchard_params: PathBuf,
    /// Orchard params handling mode: `require` (fail if missing) or `auto` (generate and persist).
    #[arg(
        long,
        env = ZAIR_ORCHARD_PARAMS_MODE,
        default_value = DEFAULT_ORCHARD_PARAMS_MODE,
        value_parser = parse_orchard_params_mode
    )]
    pub orchard_params_mode: OrchardParamsMode,
    /// Signed submission file generated by `claim sign`.
    #[arg(long, env = ZAIR_SUBMISSION_IN, default_value = DEFAULT_SUBMISSION_FILE)]
    pub submission_in: PathBuf,
    /// Shared message payload file fallback used when signing.
    #[arg(long = "message", env = ZAIR_MESSAGE_FILE, value_name = "MESSAGE_FILE")]
    pub message: Option<PathBuf>,
    /// Per-claim message assignments JSON.
    #[arg(long = "messages", env = ZAIR_MESSAGES_FILE, value_name = "MESSAGES_FILE")]
    pub messages: Option<PathBuf>,
}

/// Arguments for proof verification.
#[derive(Debug, clap::Args)]
pub struct VerifyProofArgs {
    /// Airdrop configuration file used to bind expected roots and scheme.
    #[arg(
        long,
        env = ZAIR_CONFIG_FILE,
        value_name = "CONFIG_FILE",
        default_value = DEFAULT_CONFIG_FILE
    )]
    pub config: PathBuf,
    /// Path to the Sapling verifying key file.
    #[arg(
        long = "sapling-vk",
        env = ZAIR_SAPLING_VK_FILE,
        value_name = "SAPLING_VK_FILE",
        default_value = DEFAULT_SAPLING_VK_FILE
    )]
    pub sapling_vk: PathBuf,
    /// Path to the Orchard Halo2 params file.
    #[arg(
        long,
        env = ZAIR_ORCHARD_PARAMS_FILE,
        value_name = "ORCHARD_PARAMS_FILE",
        default_value = DEFAULT_ORCHARD_PARAMS_FILE
    )]
    pub orchard_params: PathBuf,
    /// Orchard params handling mode: `require` (fail if missing) or `auto` (generate and persist).
    #[arg(
        long,
        env = ZAIR_ORCHARD_PARAMS_MODE,
        default_value = DEFAULT_ORCHARD_PARAMS_MODE,
        value_parser = parse_orchard_params_mode
    )]
    pub orchard_params_mode: OrchardParamsMode,
    /// JSON file containing claim proofs.
    #[arg(long, env = ZAIR_PROOFS_IN, default_value = DEFAULT_PROOFS_FILE)]
    pub proofs_in: PathBuf,
}

/// Arguments for signature verification.
#[derive(Debug, clap::Args)]
pub struct VerifySignatureArgs {
    /// Airdrop configuration file used to bind expected target-id and pool.
    #[arg(
        long,
        env = ZAIR_CONFIG_FILE,
        value_name = "CONFIG_FILE",
        default_value = DEFAULT_CONFIG_FILE
    )]
    pub config: PathBuf,
    /// Signed submission file generated by `claim sign`.
    #[arg(long, env = ZAIR_SUBMISSION_IN, default_value = DEFAULT_SUBMISSION_FILE)]
    pub submission_in: PathBuf,
    /// Shared message payload file fallback used when signing.
    #[arg(long = "message", env = ZAIR_MESSAGE_FILE, value_name = "MESSAGE_FILE")]
    pub message: Option<PathBuf>,
    /// Per-claim message assignments JSON.
    #[arg(long = "messages", env = ZAIR_MESSAGES_FILE, value_name = "MESSAGES_FILE")]
    pub messages: Option<PathBuf>,
}

/// Verify command group.
#[derive(Debug, clap::Subcommand)]
pub enum VerifyCommands {
    /// Recommended end-to-end verification:
    /// `verify proof -> verify signature`.
    #[command(group(
        clap::ArgGroup::new("message_input")
            .args(["message", "messages"])
            .required(true)
            .multiple(true)
    ))]
    Run {
        #[command(flatten)]
        args: VerifyRunArgs,
    },
    /// Verify claim proofs from a proofs file.
    Proof {
        #[command(flatten)]
        args: VerifyProofArgs,
    },
    /// Verify signatures in a signed claim submission.
    #[command(group(
        clap::ArgGroup::new("message_input")
            .args(["message", "messages"])
            .required(true)
            .multiple(true)
    ))]
    Signature {
        #[command(flatten)]
        args: VerifySignatureArgs,
    },
}
