//! Verify subcommands.

use std::path::PathBuf;

use zair_sdk::commands::OrchardParamsMode;

use super::parse_orchard_params_mode;

/// Arguments for end-to-end verification.
#[derive(Debug, clap::Args)]
pub struct VerifyRunArgs {
    /// Airdrop configuration file used for proof/signature binding checks.
    #[arg(
        long,
        env = "CONFIG_FILE",
        value_name = "CONFIG_FILE",
        default_value = "config.json"
    )]
    pub config: PathBuf,
    /// Path to the Sapling verifying key file.
    #[arg(
        long = "sapling-vk",
        env = "SAPLING_VK_FILE",
        value_name = "SAPLING_VK_FILE",
        default_value = "setup-sapling-vk.params"
    )]
    pub sapling_vk: PathBuf,
    /// Path to the Orchard Halo2 params file.
    #[arg(
        long,
        env = "ORCHARD_PARAMS_FILE",
        value_name = "ORCHARD_PARAMS_FILE",
        default_value = "setup-orchard-params.bin"
    )]
    pub orchard_params: PathBuf,
    /// Orchard params handling mode: `require` (fail if missing) or `auto` (generate and persist).
    #[arg(
        long,
        env = "ORCHARD_PARAMS_MODE",
        default_value = "auto",
        value_parser = parse_orchard_params_mode
    )]
    pub orchard_params_mode: OrchardParamsMode,
    /// Signed submission file generated by `claim sign`.
    #[arg(long, env = "SUBMISSION_IN", default_value = "claim-submission.json")]
    pub submission_in: PathBuf,
    /// Shared message payload file fallback used when signing.
    #[arg(long = "message", env = "MESSAGE_FILE", value_name = "MESSAGE_FILE")]
    pub message: Option<PathBuf>,
    /// Per-claim message assignments JSON.
    #[arg(long = "messages", env = "MESSAGES_FILE", value_name = "MESSAGES_FILE")]
    pub messages: Option<PathBuf>,
}

/// Arguments for proof verification.
#[derive(Debug, clap::Args)]
pub struct VerifyProofArgs {
    /// Airdrop configuration file used to bind expected roots and scheme.
    #[arg(
        long,
        env = "CONFIG_FILE",
        value_name = "CONFIG_FILE",
        default_value = "config.json"
    )]
    pub config: PathBuf,
    /// Path to the Sapling verifying key file.
    #[arg(
        long = "sapling-vk",
        env = "SAPLING_VK_FILE",
        value_name = "SAPLING_VK_FILE",
        default_value = "setup-sapling-vk.params"
    )]
    pub sapling_vk: PathBuf,
    /// Path to the Orchard Halo2 params file.
    #[arg(
        long,
        env = "ORCHARD_PARAMS_FILE",
        value_name = "ORCHARD_PARAMS_FILE",
        default_value = "setup-orchard-params.bin"
    )]
    pub orchard_params: PathBuf,
    /// Orchard params handling mode: `require` (fail if missing) or `auto` (generate and persist).
    #[arg(
        long,
        env = "ORCHARD_PARAMS_MODE",
        default_value = "auto",
        value_parser = parse_orchard_params_mode
    )]
    pub orchard_params_mode: OrchardParamsMode,
    /// JSON file containing claim proofs.
    #[arg(long, env = "PROOFS_IN", default_value = "claim-proofs.json")]
    pub proofs_in: PathBuf,
}

/// Arguments for signature verification.
#[derive(Debug, clap::Args)]
pub struct VerifySignatureArgs {
    /// Airdrop configuration file used to bind expected target-id and pool.
    #[arg(
        long,
        env = "CONFIG_FILE",
        value_name = "CONFIG_FILE",
        default_value = "config.json"
    )]
    pub config: PathBuf,
    /// Signed submission file generated by `claim sign`.
    #[arg(long, env = "SUBMISSION_IN", default_value = "claim-submission.json")]
    pub submission_in: PathBuf,
    /// Shared message payload file fallback used when signing.
    #[arg(long = "message", env = "MESSAGE_FILE", value_name = "MESSAGE_FILE")]
    pub message: Option<PathBuf>,
    /// Per-claim message assignments JSON.
    #[arg(long = "messages", env = "MESSAGES_FILE", value_name = "MESSAGES_FILE")]
    pub messages: Option<PathBuf>,
}

/// Verify command group.
#[derive(Debug, clap::Subcommand)]
pub enum VerifyCommands {
    /// Recommended end-to-end verification:
    /// `verify proof -> verify signature`.
    #[command(group(
        clap::ArgGroup::new("message_input")
            .args(["message", "messages"])
            .required(true)
            .multiple(true)
    ))]
    Run {
        #[command(flatten)]
        args: VerifyRunArgs,
    },
    /// Verify claim proofs from a proofs file.
    Proof {
        #[command(flatten)]
        args: VerifyProofArgs,
    },
    /// Verify signatures in a signed claim submission.
    #[command(group(
        clap::ArgGroup::new("message_input")
            .args(["message", "messages"])
            .required(true)
            .multiple(true)
    ))]
    Signature {
        #[command(flatten)]
        args: VerifySignatureArgs,
    },
}
