name: Setup Patched Dependencies
description: Clone and patch orchard, sapling-crypto, and halo2_gadgets repositories

runs:
  using: composite
  steps:
    - name: Clone orchard
      shell: bash
      run: |
        git clone --branch v0.11.0 --single-branch \
          https://github.com/zcash/orchard.git .patched-orchard
    - name: Patch orchard
      shell: bash
      run: |
        git -C .patched-orchard apply "../nix/airdrop-orchard-nullifier.patch"
    - name: Clone sapling-crypto
      shell: bash
      run: |
        git clone --branch v0.5.0 --single-branch \
          https://github.com/zcash/sapling-crypto.git .patched-sapling-crypto
    - name: Patch sapling-crypto
      shell: bash
      run: |
        git -C .patched-sapling-crypto apply \
          "../nix/airdrop-sapling-nullifier.patch"
    - name: Download halo2_gadgets from crates.io
      shell: bash
      run: |
        curl -sL https://static.crates.io/crates/halo2_gadgets/halo2_gadgets-0.3.1.crate \
          | tar xz
        mv halo2_gadgets-0.3.1 .patched-halo2-gadgets
    - name: Patch halo2_gadgets
      shell: bash
      run: |
        patch -p1 -d .patched-halo2-gadgets \
          < nix/airdrop-halo2-gadgets-sha256.patch
